<a href="https://colab.research.google.com/github/polanco04/3603-DataScience/blob/main/Practice/numpy/numpyPractice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Match analysis using numpy
The point of this notebook is to practice using numpy.

I create fake data and analyze it using numpy functions such as mean, max, masking, etc.

I know this is not all the data a football match has. This is just practice

##Initialization

In [90]:
import numpy as np

In [91]:
# creating a random number generator
rng = np.random.default_rng(seed=23)

In [92]:
# creating arrays of goals scored, goals conceded, shots, and possesion
goalsScored = rng.integers(0, 6, size=100)
goalsConceded = rng.integers(0, 6, size=100)
shots = rng.integers(5, 20, size=100)
possesion = np.around(rng.uniform(30, 70, size=100), 2)

In [93]:
# stacking the arrays into one 100x4 array
matches = np.column_stack((shots, goalsScored, goalsConceded, possesion))
matches

array([[18.  ,  0.  ,  3.  , 30.73],
       [15.  ,  4.  ,  1.  , 55.2 ],
       [ 6.  ,  2.  ,  2.  , 54.95],
       [15.  ,  3.  ,  2.  , 66.97],
       [19.  ,  1.  ,  1.  , 33.91],
       [ 5.  ,  0.  ,  5.  , 44.08],
       [16.  ,  3.  ,  1.  , 60.39],
       [ 5.  ,  0.  ,  1.  , 43.94],
       [17.  ,  0.  ,  1.  , 41.66],
       [ 9.  ,  3.  ,  4.  , 37.18],
       [10.  ,  3.  ,  4.  , 30.81],
       [13.  ,  5.  ,  0.  , 51.16],
       [10.  ,  2.  ,  5.  , 32.56],
       [17.  ,  1.  ,  3.  , 48.77],
       [18.  ,  1.  ,  3.  , 59.34],
       [11.  ,  1.  ,  2.  , 46.75],
       [16.  ,  0.  ,  0.  , 54.33],
       [ 8.  ,  4.  ,  1.  , 68.12],
       [15.  ,  4.  ,  0.  , 37.18],
       [14.  ,  2.  ,  2.  , 55.74],
       [19.  ,  4.  ,  2.  , 56.78],
       [19.  ,  2.  ,  5.  , 50.35],
       [16.  ,  4.  ,  1.  , 43.65],
       [12.  ,  2.  ,  3.  , 36.51],
       [ 9.  ,  2.  ,  3.  , 45.1 ],
       [13.  ,  0.  ,  3.  , 52.15],
       [ 6.  ,  1.  ,  3.  , 68.9 ],
 

## Analysis

In [94]:
# computing the data analysis
avgGoalsScored = np.mean(matches[:,1])
avgGoalsConceded = np.mean(matches[:, 2])
avgShots = np.mean(matches[:,0])
maxShots = np.max(matches[:,0])
minShots = np.min(matches[:, 0])
goalDifference =  matches[:,1] - matches[:, 2]

In [95]:
avgGoalsScored

np.float64(2.18)

In [96]:
avgGoalsConceded

np.float64(2.39)

In [97]:
avgShots

np.float64(12.44)

In [98]:
maxShots

np.float64(19.0)

In [99]:
minShots

np.float64(5.0)

In [100]:
goalDifference

array([-3.,  3.,  0.,  1.,  0., -5.,  2., -1., -1., -1., -1.,  5., -3.,
       -2., -2., -1.,  0.,  3.,  4.,  0.,  2., -3.,  3., -1., -1., -3.,
       -2., -2., -5., -2., -2.,  2., -2.,  3., -1.,  0., -5.,  1., -4.,
        3., -2., -5., -1.,  2.,  1., -1.,  4.,  4., -3.,  1.,  0., -3.,
       -4.,  4.,  4., -3., -3.,  2., -3.,  2., -5.,  1., -2.,  0., -5.,
        1.,  0.,  1.,  5.,  0., -4., -2., -1.,  0.,  3., -3.,  1.,  4.,
        5., -2., -1.,  4., -3.,  0.,  2.,  0.,  2., -2.,  4.,  4.,  0.,
        3., -2.,  4.,  0., -3.,  3., -5., -1., -2.])

In [101]:
# adding goal difference to matches
matches = np.column_stack((matches, goalDifference))

In [102]:
matches

array([[18.  ,  0.  ,  3.  , 30.73, -3.  ],
       [15.  ,  4.  ,  1.  , 55.2 ,  3.  ],
       [ 6.  ,  2.  ,  2.  , 54.95,  0.  ],
       [15.  ,  3.  ,  2.  , 66.97,  1.  ],
       [19.  ,  1.  ,  1.  , 33.91,  0.  ],
       [ 5.  ,  0.  ,  5.  , 44.08, -5.  ],
       [16.  ,  3.  ,  1.  , 60.39,  2.  ],
       [ 5.  ,  0.  ,  1.  , 43.94, -1.  ],
       [17.  ,  0.  ,  1.  , 41.66, -1.  ],
       [ 9.  ,  3.  ,  4.  , 37.18, -1.  ],
       [10.  ,  3.  ,  4.  , 30.81, -1.  ],
       [13.  ,  5.  ,  0.  , 51.16,  5.  ],
       [10.  ,  2.  ,  5.  , 32.56, -3.  ],
       [17.  ,  1.  ,  3.  , 48.77, -2.  ],
       [18.  ,  1.  ,  3.  , 59.34, -2.  ],
       [11.  ,  1.  ,  2.  , 46.75, -1.  ],
       [16.  ,  0.  ,  0.  , 54.33,  0.  ],
       [ 8.  ,  4.  ,  1.  , 68.12,  3.  ],
       [15.  ,  4.  ,  0.  , 37.18,  4.  ],
       [14.  ,  2.  ,  2.  , 55.74,  0.  ],
       [19.  ,  4.  ,  2.  , 56.78,  2.  ],
       [19.  ,  2.  ,  5.  , 50.35, -3.  ],
       [16.  ,  4.  ,  1.  , 43.

In [103]:
# matches where possession was greater than or equal to 50%
matchesFifty = matches[:,3] >= 50.0
nMatchesFifty = np.count_nonzero(matchesFifty)

In [104]:
matchesFifty

array([False,  True,  True,  True, False, False,  True, False, False,
       False, False,  True, False, False,  True, False,  True,  True,
       False,  True,  True,  True, False, False, False,  True,  True,
       False,  True,  True, False,  True, False,  True, False, False,
        True,  True,  True,  True, False,  True, False,  True, False,
        True, False, False,  True, False, False,  True, False, False,
        True,  True,  True, False,  True, False,  True,  True,  True,
       False,  True, False,  True, False, False, False,  True,  True,
       False,  True, False,  True,  True, False,  True,  True,  True,
       False, False,  True, False,  True, False,  True, False, False,
       False, False,  True,  True, False,  True,  True,  True, False,
        True])

In [105]:
nMatchesFifty

52

In [106]:
# matches where goal difference is more than 1
diffOne = np.abs(matches[:,1] - matches[:,2]) > 1
ndiffOne = np.count_nonzero(diffOne)

In [107]:
diffOne

array([ True,  True, False, False, False,  True,  True, False, False,
       False, False,  True,  True,  True,  True, False, False,  True,
        True, False,  True,  True,  True, False, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False, False,
        True, False,  True,  True,  True,  True, False,  True, False,
       False,  True,  True,  True, False, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
       False,  True, False, False, False,  True, False,  True,  True,
       False, False,  True,  True, False,  True,  True,  True, False,
        True,  True, False,  True, False,  True,  True,  True,  True,
       False,  True,  True,  True, False,  True,  True,  True, False,
        True])

In [108]:
ndiffOne

65

In [109]:
# matches where number of shots is higher than the average
moreShotAvg =  matches[:, 0] > avgShots
nShotAvg = np.count_nonzero(moreShotAvg)

In [110]:
moreShotAvg

array([ True,  True, False,  True,  True, False,  True, False,  True,
       False, False,  True, False,  True,  True, False,  True, False,
        True,  True,  True,  True,  True, False, False,  True, False,
       False, False,  True,  True, False, False,  True,  True, False,
        True,  True,  True, False, False,  True, False,  True, False,
        True,  True, False, False, False,  True,  True, False,  True,
       False,  True, False,  True,  True, False,  True,  True,  True,
       False, False, False,  True, False,  True, False, False, False,
        True, False, False,  True, False, False,  True, False,  True,
        True,  True, False, False,  True,  True,  True, False,  True,
       False,  True, False,  True, False, False, False, False, False,
        True])

In [111]:
nShotAvg

51

In [112]:
# making results array (-1 = loss, 0 = draw, 1 = win)
result = np.sign(goalDifference)
result

array([-1.,  1.,  0.,  1.,  0., -1.,  1., -1., -1., -1., -1.,  1., -1.,
       -1., -1., -1.,  0.,  1.,  1.,  0.,  1., -1.,  1., -1., -1., -1.,
       -1., -1., -1., -1., -1.,  1., -1.,  1., -1.,  0., -1.,  1., -1.,
        1., -1., -1., -1.,  1.,  1., -1.,  1.,  1., -1.,  1.,  0., -1.,
       -1.,  1.,  1., -1., -1.,  1., -1.,  1., -1.,  1., -1.,  0., -1.,
        1.,  0.,  1.,  1.,  0., -1., -1., -1.,  0.,  1., -1.,  1.,  1.,
        1., -1., -1.,  1., -1.,  0.,  1.,  0.,  1., -1.,  1.,  1.,  0.,
        1., -1.,  1.,  0., -1.,  1., -1., -1., -1.])

In [113]:
# adding results to matches
matches = np.column_stack((matches, result))

In [114]:
matches

array([[18.  ,  0.  ,  3.  , 30.73, -3.  , -1.  ],
       [15.  ,  4.  ,  1.  , 55.2 ,  3.  ,  1.  ],
       [ 6.  ,  2.  ,  2.  , 54.95,  0.  ,  0.  ],
       [15.  ,  3.  ,  2.  , 66.97,  1.  ,  1.  ],
       [19.  ,  1.  ,  1.  , 33.91,  0.  ,  0.  ],
       [ 5.  ,  0.  ,  5.  , 44.08, -5.  , -1.  ],
       [16.  ,  3.  ,  1.  , 60.39,  2.  ,  1.  ],
       [ 5.  ,  0.  ,  1.  , 43.94, -1.  , -1.  ],
       [17.  ,  0.  ,  1.  , 41.66, -1.  , -1.  ],
       [ 9.  ,  3.  ,  4.  , 37.18, -1.  , -1.  ],
       [10.  ,  3.  ,  4.  , 30.81, -1.  , -1.  ],
       [13.  ,  5.  ,  0.  , 51.16,  5.  ,  1.  ],
       [10.  ,  2.  ,  5.  , 32.56, -3.  , -1.  ],
       [17.  ,  1.  ,  3.  , 48.77, -2.  , -1.  ],
       [18.  ,  1.  ,  3.  , 59.34, -2.  , -1.  ],
       [11.  ,  1.  ,  2.  , 46.75, -1.  , -1.  ],
       [16.  ,  0.  ,  0.  , 54.33,  0.  ,  0.  ],
       [ 8.  ,  4.  ,  1.  , 68.12,  3.  ,  1.  ],
       [15.  ,  4.  ,  0.  , 37.18,  4.  ,  1.  ],
       [14.  ,  2.  ,  2.  , 55